### PR TITLE
COBOLParser changes

### LINKED ISSUE #493: COBOL import - SEARCH issues
1. incomplete / invalid sources result in NullPointerExceptions
The reason for this is that `importSearch` just "expects" the `CobVar`s to be found.

2. the import for `SEARCH VARYING` was wrong, assuming a different index to be changed (it is *additional* changed).

### PR DESCRIPTION
**Pull request by GitMensch**
* importSearch fixed #493:
  * fixed NullPointerException when variables are unknown (for example only partial source parsed)
  * fixed PROD_SEARCH_VARYING_VARYING to increment an *additional* index/number
* PROD_START_STATEMENT_START - added with TODO not-supported
* PROD_EXIT_BODY_PERFORM_CYCLE: include as not-supported "continue" JUMP (see #64) as it can be better understand by non-COBOL programmers (and *may* even work with some exports)

### CODE REVIEW

File: src/lu/fisch/structorizer/parsers/COBOLParser.java [hunk 1]
```diff
@@ -5750,36 +5760,60 @@ private boolean accomplishPrevSoP(Subqueue _parentNode, SoPTarget _what) {
...
+			if (redBody.get(1).asReduction().getParent().getTableIndex() == RuleConstants.PROD_SEARCH_VARYING_VARYING) {
+				String indexAdditionalName = this.getContent_R(redBody.get(1).asReduction().get(1).asReduction(), "");
+				indexAdditionalVar = this.currentProg.getCobVar(indexAdditionalName);
+				if (indexAdditionalVar == null) {
+					System.out.println("Warning, couldn't get the index variable \"" + indexAdditionalName + "\"!");
+					indexAdditionalVar = this.cobTools.new CobVar(indexAdditionalName, table);
+				}
+			}
+			// In case we could identify an index variable we might possibly use
+			// a FOR-IN loop?
```
Comment (codemanyak) [inline src/lu/fisch/structorizer/parsers/COBOLParser.java]: I think the comment wanted to say "In case we could NOT identify an index variable..."?

Comment (GitMensch) [reply src/lu/fisch/structorizer/parsers/COBOLParser.java]: It is your comment, I've just left it in ;-)
But you may move this more or less to SEARCH ALL. - sample: https://svn.code.sf.net/p/open-cobol/contrib/trunk/samples/cgiform/cgiform.cob
